server.port=8085
spring.application.name=cards

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Enable the H2 web interface
spring.h2.console.path=/h2-console

# Inter-Service Feign & Circuit Breaker Configurations
account.service.url=http://localhost:8080
spring.cloud.openfeign.circuitbreaker.enabled=true

# Cards Business Properties
card.bin=000654
card.pan.secret=qwerty1234321)9!Xag
card.fee.account=admin.cards@test.com
card.expiry=2
card.default.limit=100000